version: "3.1"

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  cache:
    image: redis:6.2-bullseye
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

  courier-location-microservice:
    image: index.docker.io/msinancoskun/courier-location-microservice:latest
    container_name: "courier-location-microservice"
    restart: always
    depends_on:
      - kafka
      - cache
    environment:
      MONGODB_URI: ${MONGODB_URI}
      NODE_ENV: "production"
      KAFKA_URL: "kafka:9092"
      PORT: "3000"
    ports:
      - 3000:3000
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"